UI update: Sidebar
PeytonBoggs/todo-list-web pull request #8
Opened 2023-07-11 20:31 UTC by PeytonBoggs

This branch integrates Chakra-UI into the application to create a much more user-friendly interface. This PR is for the sidebar of the interface - a column of components that include the app header, add tasks card, search tasks card, and delete tasks button. All components of the application are still fully functioning, there were a few changes in logic that had to be made, but this is a largely aesthetic update.

![Screenshot 2023-07-11 at 4 30 02 PM](https://github.com/PeytonBoggs/todo-list-web/assets/129628668/20ec2675-2efe-4fd9-8a31-18e746f2154f)

2023-07-12 18:16 UTC, PeytonBoggs commented
![Screenshot 2023-07-12 at 2 15 53 PM](https://github.com/PeytonBoggs/todo-list-web/assets/129628668/8a60a6be-a0e7-4a45-89c7-f6f5950bce04)

2023-07-12 19:43 UTC, WesleyChenRTS2 commented on src/AppHeader.tsx
> +        <Card margin="5%" bg="#E0FFD6" border="3px solid green">
instead of using 5% to make it dynamic, https://chakra-ui.com/docs/styled-system/responsive-styles follow this guide to make them responsive based on breakpoints. I personally like the look of margin={[2, 3, 4]} (these are static i believe) but you can use 'em' or 'px' depending if you want relative or static measurements.

2023-07-12 19:44 UTC, WesleyChenRTS2 commented on src/DeleteTask.tsx
> +          <Button width="100%" bg="#FFD6E0" border="2px solid red" _hover={{backgroundColor:"#FFB5C7"}} onClick={() => {handleDeleteClick(taskID); toast({variant:"left-accent", position:"top-right",
let's move this entire onClick call to its own function, or move the toast call to be ran inside the handleDeleteClick function.

2023-07-12 19:44 UTC, WesleyChenRTS2 commented on src/DeleteTasks.tsx
> +    const [, setDeleteMessage] = useState<string>("")
what's the point of setDeleteMessage if we don't use the state?

2023-07-12 19:45 UTC, WesleyChenRTS2 commented on src/PostTask.tsx
> +    const [, setAddMessage] = useState<string>("");
same thing here, are we not using the state?

2023-07-12 19:46 UTC, WesleyChenRTS2 commented on src/PostTask.tsx
> +            <Card width="90%" border="3px solid grey" margin="5%" padding="10px">
to each their own but i'm not vibing with all these percentages

2023-07-12 19:46 UTC, WesleyChenRTS2 commented on src/SearchBar.tsx
>              setSearchedTask({id: 0, title: searchedTask.title, complete: searchedTask.complete});
what is this doing

2023-07-12 19:47 UTC, WesleyChenRTS2 commented on src/SearchBar.tsx
> +                        <NumberInput width="80%" defaultValue={NaN} min={0} onChange={(valueString) => handleIDChange(valueString)}>
this can just be ``onChange={handleIDChange}>``

2023-07-12 20:22 UTC, PeytonBoggs commented
![Screenshot 2023-07-12 at 4 22 07 PM](https://github.com/PeytonBoggs/todo-list-web/assets/129628668/c424a98a-12c6-4cda-8cd8-c46510e68248)

![Screenshot 2023-07-12 at 4 22 19 PM](https://github.com/PeytonBoggs/todo-list-web/assets/129628668/15e9e6b4-4af4-4bd0-a668-520c22d090cc)

2023-07-13 12:42 UTC, PeytonBoggs commented on src/SearchBar.tsx
>              setSearchedTask({id: 0, title: searchedTask.title, complete: searchedTask.complete});
It checks if the value of the searched ID (given in the search bar) is blank - if so, it sets the ID of the searched task to 0, which, in the API, returns tasks with all IDs. If this check were not in place, it would set the ID of the searched task to NaN, which would give an error, whenever the search bar's ID input was blank.

2023-07-13 14:07 UTC, matt-j-deasy requested changes

2023-07-13 14:07 UTC, matt-j-deasy commented on src/AppHeader.tsx
> +                <Heading color="blackAlpha.700" fontSize="4xl" padding="20px" mr="-10px">
padding px here is bad. Use rem

2023-07-13 14:07 UTC, matt-j-deasy commented on src/DeleteTask.tsx
> +          <Button width="100%" bg="#FFD6E0" border="2px solid red" _hover={{backgroundColor:"#FFB5C7"}} onClick={() => handleDeleteClick(taskID)}>
Using pixels in borders is fine

2023-07-13 14:07 UTC, matt-j-deasy commented on src/DeleteTasks.tsx
> +            <Button width="90%" bg="#FFD6E0" border="3px solid red" _hover={{bg:"#FFB5C7"}} margin="5%" onClick={() => handleDeleteTasksClick()}>Delete All Tasks</Button>
Percentages here is bad. Also you probably don't want your button to be 90%, I would try to accmplish what you want with margin and padding or flex box

2023-07-13 14:07 UTC, matt-j-deasy commented on src/PostTask.tsx
> +                    <HStack width="90%" padding="10px" paddingLeft="0">
Width 90% again here. You are probably looking for margin-x property here

2023-07-13 14:07 UTC, matt-j-deasy commented on src/PostTask.tsx
> +                        <Text fontSize="20" width="20%" padding="10px">Title:</Text>
Having width % on text is probably wrong too. Again look at margins and padding

2023-07-13 15:33 UTC, PeytonBoggs commented
![Screenshot 2023-07-13 at 11 33 15 AM](https://github.com/PeytonBoggs/todo-list-web/assets/129628668/dde26aef-b6d9-420e-876e-8840dd1a5dfd)

2023-07-13 17:37 UTC, WesleyChenRTS2 commented on src/DeleteTasks.tsx
> +            })
Two things here:
this seems more like a success toast, so maybe we want to change the status to reflect that. If you're using 'error' for the color, look into chakra to figure out how to change the color of a success toast.

second thing, since onTasksDeleted is an API call that should resolve, we can turn the onTasksDeleted function to an async function that returns a promise. OR, I would recommend moving the toast operation to where the onTasksDeleted function lives.

2023-07-13 17:37 UTC, WesleyChenRTS2 commented on src/PostTask.tsx
> +            onTaskAdded();
same thing here

2023-07-13 20:17 UTC, PeytonBoggs commented
<img width="1904" alt="Screenshot 2023-07-13 at 4 16 54 PM" src="https://github.com/PeytonBoggs/todo-list-web/assets/129628668/75e3a52d-f7f3-4129-8d8e-6ecd094c0763">

2023-07-17 14:22 UTC, WesleyChenRTS2 approved these changes

2023-07-19 18:13 UTC, matt-j-deasy approved these changes

2023-07-19 18:16 UTC, merged